name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials for the job
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region if different

      # Step 3: Verify that AWS credentials are working by getting caller identity
      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      # Step 4: Sync the repository files to your S3 bucket
      - name: Sync files to S3
        run: aws s3 sync . s3://cloud-profile-website --delete

      # Step 5: Invalidate CloudFront cache so your changes appear immediately
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2WHBNJ48QORRA --paths "/*"
